### ISSUE TITLE
Example 2 uses datafile "bank2.dat". Should we add this file to this repository/meta-info?

### ISSUE THREAD

**Issue by polarstern** [QuantLet/QID-2244-ppsib#2]

**Comment by lborke** [comment]
Yes, this datafile should also be added to the Repo.
In future all files which are needed for any part of the code should be in the repo, and also all plots generated by the code, independently from being commented or not.

**Comment by polarstern** [comment]
Ok, then should we add this datafile to meta-info?

**Comment by lborke** [comment]
I would suggest the following format (meta info header):
# Datafile [example]: Name....

to emphasize that this datafile is optional.

**Comment by Tdannen** [comment]
info is not included in metaInfo or am I mistaken.

file is uploaded. 

should this issue be closed then?

**Comment by polarstern** [comment]
Yes, it was not included because I read the answer right now and corrected it right now.
The procedure:
- I ask a question and assign it to Lukas
- Then some options are possible:
   - He answers, I read and correct it and close issue
   - He answers, corrects and closes issue
   - ...smth more complicated
So if I didn't correct it according to the answer, it's not really good idea to close issue ;-)
